# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 02167fac2db45ef99fb6c3572eed8c304f6a8ad3f295ddb3a4ab420b5b4c92a9148b237298209fc49d631f37f886038aa508e840adefaea7bc2f499127bab284

test:
  secret_key_base: c6590f78d14267de5d3842a6331ba2d3a38ebbd5777d7eaf5703d69e717968d1bfe4d704146987d38564beed8b442f610b4f95a88c206dc480397d18f34f9ecf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
